name: Terraform deploy

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string
      backend-config:
        required: true
        type: string
      args:
        required: true
        type: string
      working-directory:
        default: "."
        required: false
        type: string
      action:
        default: "plan" # plan or apply
        required: false
        type: string
      oci-region:
        required: true
        type: string
    secrets:
      TF_VAR_FINGERPRINT:
        required: false
      TF_VAR_TENANCY_OCID:
        required: false
      TF_VAR_USER_OCID:
        required: false
      TF_VAR_PRIVATE_KEY:
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  terraform-action:
    name: Terraform ${{ inputs.action }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_fingerprint:  ${{ secrets.TF_VAR_FINGERPRINT }}
      TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_TENANCY_OCID }}
      TF_VAR_user_ocid:    ${{ secrets.TF_VAR_USER_OCID }}
      TF_VAR_private_key:  ${{ secrets.TF_VAR_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: deploy
          role-skip-session-tagging: true

      - name: Install OCI CLI
        run: pip install oci-cli --quiet

      - name: Setup OCI config
        run: |
          mkdir -p ~/.oci
          cat <<EOF > ~/.oci/config
          [DEFAULT]
          user=${{ secrets.TF_VAR_USER_OCID }}
          fingerprint=${{ secrets.TF_VAR_FINGERPRINT }}
          tenancy=${{ secrets.TF_VAR_TENANCY_OCID }}
          region=${{ inputs.oci-region }}
          key_file=~/.oci/oci_api_key.pem
          EOF

          echo "${{ secrets.TF_VAR_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Terraform init
        run: terraform init -backend-config="${{ inputs.backend-config }}"
        working-directory: ${{ inputs.working-directory }}

      - name: Terraform ${{ inputs.action }}
        run: |
          if [[ "${{ inputs.action }}" == "plan" ]]; then
            terraform plan ${{ inputs.args }}
          elif [[ "${{ inputs.action }}" == "apply" ]]; then
            terraform apply ${{ inputs.args }} -auto-approve
          fi
        working-directory: ${{ inputs.working-directory }}