name: Terraform CI

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform version
      run: terraform --version

    - name: Terraform fmt
      run: terraform fmt -check -diff -recursive

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: TFLint version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: TFLint check
      run: tflint
